from langchain_core.tools import tool
from langchain_core.messages import ToolMessage
from app.agents.state import AgentState

def get_retriever_node(chatbot_instance):
    """
    Returns the retrieval execution node and tools list bound to the chatbot instance.
    This avoids circular imports and re-uses existing database connections and embeddings.
    """
    
    @tool
    def vector_search(query: str) -> str:
        """Search Umer's resume, work experience, education, projects, and repository code files for general queries or semantic lookups."""
        docs = chatbot_instance.retriever.invoke(query)
        formatted_docs = []
        for d in docs:
            formatted_docs.append(
                f"--- Document Source: {d.metadata.get('source_path', 'Unknown')} ---\n{d.page_content}"
            )
        return "\n\n".join(formatted_docs)

    @tool
    def graph_search(query: str) -> str:
        """Query the knowledge graph for relationships, dates, and technology stack mappings (e.g. which projects Umer built with React)."""
        return chatbot_instance.graph_service.query_graph(query)

    tools = [vector_search, graph_search]

    def execute_retriever(state: AgentState) -> dict:
        """
        Executes any tool calls generated by the planner node and saves the retrieved
        context blocks to the graph state.
        """
        last_message = state["messages"][-1]
        retrieved_docs = []
        graph_context = ""
        tool_messages = []

        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            for tool_call in last_message.tool_calls:
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]
                query = tool_args.get("query", "")

                if tool_name == "vector_search":
                    # Get raw docs for citations/downstream and run tool
                    docs = chatbot_instance.retriever.invoke(query)
                    for doc in docs:
                        retrieved_docs.append({
                            "page_content": doc.page_content,
                            "metadata": doc.metadata
                        })
                    result = vector_search.invoke(tool_args)
                elif tool_name == "graph_search":
                    result = graph_search.invoke(tool_args)
                    graph_context = result
                else:
                    result = f"Error: Tool '{tool_name}' not found."

                tool_messages.append(ToolMessage(
                    content=str(result),
                    name=tool_name,
                    tool_call_id=tool_call["id"]
                ))

        return {
            "messages": tool_messages,
            "retrieved_docs": retrieved_docs,
            "graph_context": graph_context
        }

    return execute_retriever, tools
